---
services:
  app:
    image: triliumnext/trilium
    environment:
      TRILIUM_DATA_DIR: /home/node/trilium-data
    networks:
      - default
    ports:
      - "8080:8080"
    volumes:
      - trilium_data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    internal: true

volumes:
  trilium_data:
